
### Создание кошелька
POST /api/v1/wallets/create
Host: localhost:9000

### Получение информации по идентификатору кошелька
GET /api/v1/wallets/cf8d91da-003c-4414-b646-ff1e1af20cf6
Host: localhost:9000

### Выполнение операции внесения и выведения денежных средств с кошелька
POST /api/v1/operations/perform
Host: localhost:9000
Content-Type: application/json

{
    "walletId": "cf8d91da-003c-4414-b646-ff1e1af20cf6",
    "amount": 3500,
    "operationType": "WITHDRAW"
}

### Получение списка произведенных операций по идентификатору кошелька
GET /api/v1/operations/by-wallet?walletId=cf8d91da-003c-4414-b646-ff1e1af20cf6
Host: localhost:9000