
### Создание кошелька
POST /api/v1/wallets/create
Host: localhost:9000

### Получение информации по идентификатору кошелька
GET /api/v1/wallets/4fe72529-4d31-4bec-b7ac-78f106636a5b
Host: localhost:9000

### Выполнение операции внесения и выведения денежных средств с кошелька
POST /api/v1/operations/perform
Host: localhost:9000
Content-Type: application/json

{
    "walletId": "4fe72529-4d31-4bec-b7ac-78f106636a5b",
    "amount": 6000,
    "operationType": "DEPOSIT"
}

### Получение списка произведенных операций по идентификатору кошелька
GET /api/v1/operations/by-wallet?walletId=4fe72529-4d31-4bec-b7ac-78f106636a5b
Host: localhost:9000