
server:
  port: 9000
spring:
  application:
    name: wallet-service
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5432/wallet_service_db
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
